
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a8
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true


KERNEL_SOURCE_PATH   := $(VMWORKS_BUILD_TOP)/kernel
TARGET_KERNEL_CONFIG := vc0718_nvd_defconfig

