LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

KERNEL_IMAGE  := arch/arm/boot/uImage
KERNEL_OUTPUT := $(LOCAL_PATH)/$(KERNEL_IMAGE)

$(KERNEL_OUTPUT)::
	make -C $(KERNEL_SOURCE_PATH) $(TARGET_KERNEL_CONFIG)
	make -C $(KERNEL_SOURCE_PATH) uImage


LOCAL_MODULE := kernel.bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := PREBUILT
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_SRC_FILES := $(KERNEL_IMAGE)
include $(BUILD_PREBUILT)

