
PRODUCT_PACKAGES +=

PRODUCT_COPY_FILES +=

PRODUCT_PROPERTY_OVERRIDES +=


PRODUCT_ROOT_SOURCE := $(VMWORKS_BUILD_TOP)/system/core/rootdir

BUSYBOX_SOURCE_PATH := $(VMWORKS_BUILD_TOP)/external/busybox
BUSYBOX_CONFIG      := vmc_vc0718_defconfig

